# Generated by Django 4.2.20 on 2025-04-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AddField(
            model_name='review',
            name='image_path',
            field=models.CharField(default='images/reviews/default.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
