# Generated by Django 4.2.20 on 2025-04-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_review_image_review_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='new_image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
