# Generated by Django 4.2.20 on 2025-04-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_review_new_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='new_image_path',
        ),
    ]
