# Generated by Django 4.2.20 on 2025-04-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='date', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
