# Generated by Django 4.2.20 on 2025-04-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social',
        ),
    ]
