# Generated by Django 4.2.20 on 2025-04-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_service_remove_user_social'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
