# Generated by Django 4.2.20 on 2025-04-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_user'),
    ]

    operations = [
    ]
