# Generated by Django 4.2.20 on 2025-04-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_review_new_image_path'),
        ('user', '0011_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceRequest',
            new_name='User',
        ),
    ]
