# Generated by Django 4.2.20 on 2025-04-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
