# Generated by Django 4.2.20 on 2025-04-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='created_at',
        ),
    ]
